n = input('Digite algo: ')
print('O tipo primitivo desse valor é: ', type(n))
print('É numérico? ', n.isnumeric())
print('É alfanumérico? ', n.isalnum())
print('Só tem espaços? ', n.isspace())
print('É alfabético? ', n.isalpha())
print('Está maiúsculas? ', n.isupper())
print('Está minúsculas? ', n.islower())
print('Está capitalizada? ', n.isidentifier())
